from __future__ import annotations

from typing import Protocol
from uuid import UUID

from agent_platform.platform.skills.entities import Skill, SkillVersion


class SkillRepository(Protocol):
    async def add(self, skill: Skill, version: SkillVersion) -> None: ...

    async def update(self, skill: Skill) -> None: ...

    async def add_version(self, version: SkillVersion) -> None: ...

    async def update_version(self, version: SkillVersion) -> None: ...

    async def get(self, *, tenant_id: UUID, skill_id: UUID) -> Skill | None: ...

    async def list_all(self, *, tenant_id: UUID) -> list[Skill]: ...

    async def get_version(
        self, *, tenant_id: UUID, skill_id: UUID, version: int
    ) -> SkillVersion | None: ...

    async def list_versions(self, *, tenant_id: UUID, skill_id: UUID) -> list[SkillVersion]: ...


class SkillStorage(Protocol):
    async def put(self, *, key: str, content: bytes) -> None: ...

    async def get(self, *, key: str) -> bytes: ...

    async def delete(self, *, key: str) -> None: ...
