from typing import Protocol
from uuid import UUID

from agent_platform.platform.tools.entities import McpServer, Tool


class ToolRepository(Protocol):
    async def add_server(self, server: McpServer) -> None: ...

    async def get_server(self, *, tenant_id: UUID, server_id: UUID) -> McpServer | None: ...

    async def list_servers(self, *, tenant_id: UUID) -> list[McpServer]: ...

    async def update_server(self, server: McpServer) -> None: ...

    async def add_tool(self, tool: Tool) -> None: ...

    async def get_tool(self, *, tenant_id: UUID, tool_id: UUID) -> Tool | None: ...

    async def list_tools(
        self, *, tenant_id: UUID, server_id: UUID | None = None
    ) -> list[Tool]: ...

    async def update_tool(self, tool: Tool) -> None: ...
