#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROFILE_NAME="${MVP_PROFILE_NAME:-agent-platform-mvp}"
RUNTIME_DIR="${MVP_PROFILE_RUNTIME_DIR:-${ROOT_DIR}/.local/mvp-profile/${PROFILE_NAME}}"
CORE_PROJECT="${PROFILE_NAME}-core"
LITELLM_PROJECT="${PROFILE_NAME}-litellm"
APP_PROJECT="${PROFILE_NAME}-app"
CORE_NETWORK_NAME="${CORE_PROJECT}_default"
LITELLM_NETWORK_NAME="${PROFILE_NAME}-llm"
CORE_COMPOSE_FILE="${ROOT_DIR}/infra/compose/core.yml"
LITELLM_COMPOSE_FILE="${ROOT_DIR}/infra/compose/litellm.yml"
LITELLM_STUB_COMPOSE_FILE="${ROOT_DIR}/infra/litellm/compose.stub.yml"
PLATFORM_COMPOSE_FILE="${ROOT_DIR}/infra/compose/platform.yml"
CORE_ENV_FILE="${RUNTIME_DIR}/core.env"
LITELLM_ENV_FILE="${RUNTIME_DIR}/litellm.env"
PLATFORM_ENV_FILE="${RUNTIME_DIR}/platform.env"
SECRETS_ENV_FILE="${RUNTIME_DIR}/secrets.env"
STARTED_FRESH=false

export CORE_NETWORK_NAME LITELLM_NETWORK_NAME

validate_profile_name() {
  if [[ ! "${PROFILE_NAME}" =~ ^[a-z0-9][a-z0-9_-]*$ ]]; then
    printf 'invalid MVP profile name: %s\n' "${PROFILE_NAME}" >&2
    return 2
  fi
}

random_secret() {
  python3 -c 'import secrets; print(secrets.token_urlsafe(32))'
}

write_environment() {
  if [[ -f "${CORE_ENV_FILE}" && -f "${LITELLM_ENV_FILE}" && -f "${PLATFORM_ENV_FILE}" ]]; then
    return
  fi

  mkdir -p "${RUNTIME_DIR}"
  chmod 700 "${RUNTIME_DIR}"
  umask 077

  if [[ ! -f "${SECRETS_ENV_FILE}" ]]; then
    local postgres_password redis_password minio_password
    local litellm_master_key litellm_worker_key litellm_db_password sandbox_secret
    postgres_password="$(random_secret)"
    redis_password="$(random_secret)"
    minio_password="$(random_secret)"
    litellm_master_key="sk-$(random_secret)"
    litellm_worker_key="sk-$(random_secret)"
    litellm_db_password="$(random_secret)"
    sandbox_secret="$(random_secret)"
    {
      printf 'POSTGRES_PASSWORD=%s\n' "${postgres_password}"
      printf 'REDIS_PASSWORD=%s\n' "${redis_password}"
      printf 'MINIO_ROOT_PASSWORD=%s\n' "${minio_password}"
      printf 'LITELLM_MASTER_KEY=%s\n' "${litellm_master_key}"
      printf 'LITELLM_WORKER_API_KEY=%s\n' "${litellm_worker_key}"
      printf 'LITELLM_DB_PASSWORD=%s\n' "${litellm_db_password}"
      printf 'SANDBOX_CONTROLLER_BEARER_SECRET=%s\n' "${sandbox_secret}"
    } >"${SECRETS_ENV_FILE}"
  fi

  # This file is generated by this script with shell-safe token_urlsafe values only.
  # shellcheck disable=SC1090
  source "${SECRETS_ENV_FILE}"

  {
    printf 'POSTGRES_DB=agent_platform\n'
    printf 'POSTGRES_USER=agent_platform\n'
    printf 'POSTGRES_PASSWORD=%s\n' "${POSTGRES_PASSWORD}"
    printf 'POSTGRES_PORT=%s\n' "${POSTGRES_PORT:-5432}"
    printf 'REDIS_PASSWORD=%s\n' "${REDIS_PASSWORD}"
    printf 'REDIS_PORT=%s\n' "${REDIS_PORT:-6379}"
    printf 'MINIO_ROOT_USER=agent_platform\n'
    printf 'MINIO_ROOT_PASSWORD=%s\n' "${MINIO_ROOT_PASSWORD}"
    printf 'MINIO_API_PORT=%s\n' "${MINIO_API_PORT:-9000}"
    printf 'MINIO_CONSOLE_PORT=%s\n' "${MINIO_CONSOLE_PORT:-9001}"
  } >"${CORE_ENV_FILE}"

  {
    printf 'LITELLM_MASTER_KEY=%s\n' "${LITELLM_MASTER_KEY}"
    printf 'LITELLM_WORKER_API_KEY=%s\n' "${LITELLM_WORKER_API_KEY}"
    printf 'LITELLM_PORT=%s\n' "${LITELLM_PORT:-4000}"
    printf 'LITELLM_DB_NAME=litellm\n'
    printf 'LITELLM_DB_USER=litellm\n'
    printf 'LITELLM_DB_PASSWORD=%s\n' "${LITELLM_DB_PASSWORD}"
    printf 'LITELLM_UPSTREAM_MODEL=openai/local-test\n'
    printf 'LITELLM_NETWORK_NAME=%s\n' "${LITELLM_NETWORK_NAME}"
  } >"${LITELLM_ENV_FILE}"

  {
    printf 'POSTGRES_DB=agent_platform\n'
    printf 'POSTGRES_USER=agent_platform\n'
    printf 'POSTGRES_PASSWORD=%s\n' "${POSTGRES_PASSWORD}"
    printf 'REDIS_PASSWORD=%s\n' "${REDIS_PASSWORD}"
    printf 'MINIO_ROOT_USER=agent_platform\n'
    printf 'MINIO_ROOT_PASSWORD=%s\n' "${MINIO_ROOT_PASSWORD}"
    printf 'PLATFORM_API_PORT=%s\n' "${PLATFORM_API_PORT:-8000}"
    printf 'PLATFORM_WEB_PORT=%s\n' "${PLATFORM_WEB_PORT:-8080}"
    printf 'OTEL_ENABLED=false\n'
    printf 'AGENT_PLATFORM_LLM_GATEWAY_URL=http://litellm:4000/v1\n'
    printf 'AGENT_PLATFORM_LLM_GATEWAY_API_KEY=%s\n' "${LITELLM_WORKER_API_KEY}"
    printf 'SANDBOX_CONTROLLER_BEARER_SECRET=%s\n' "${SANDBOX_CONTROLLER_BEARER_SECRET}"
    printf 'SANDBOX_CONTROLLER_IMAGE=python:3.12.13-slim-bookworm@sha256:8a7e7cc04fd3e2bd787f7f24e22d5d119aa590d429b50c95dfe12b3abe52f48b\n'
    printf 'DOCKER_SOCKET_PATH=/var/run/docker.sock\n'
    printf 'CORE_NETWORK_NAME=%s\n' "${CORE_NETWORK_NAME}"
    printf 'LITELLM_NETWORK_NAME=%s\n' "${LITELLM_NETWORK_NAME}"
  } >"${PLATFORM_ENV_FILE}"
}

load_environment() {
  if [[ ! -f "${CORE_ENV_FILE}" || ! -f "${LITELLM_ENV_FILE}" || ! -f "${PLATFORM_ENV_FILE}" ]]; then
    printf 'MVP profile is not initialized: %s\n' "${RUNTIME_DIR}" >&2
    return 2
  fi
  set -a
  # These files are generated by this script and contain no executable expressions.
  # shellcheck disable=SC1090
  source "${CORE_ENV_FILE}"
  # shellcheck disable=SC1090
  source "${LITELLM_ENV_FILE}"
  # shellcheck disable=SC1090
  source "${PLATFORM_ENV_FILE}"
  set +a
  export CORE_NETWORK_NAME LITELLM_NETWORK_NAME
}

core_compose() {
  docker compose -p "${CORE_PROJECT}" --env-file "${CORE_ENV_FILE}" \
    -f "${CORE_COMPOSE_FILE}" "$@"
}

litellm_compose() {
  docker compose -p "${LITELLM_PROJECT}" --env-file "${LITELLM_ENV_FILE}" \
    -f "${LITELLM_COMPOSE_FILE}" -f "${LITELLM_STUB_COMPOSE_FILE}" "$@"
}

app_compose() {
  docker compose -p "${APP_PROJECT}" --env-file "${PLATFORM_ENV_FILE}" \
    -f "${PLATFORM_COMPOSE_FILE}" --profile worker "$@"
}

ensure_llm_network() {
  local owner
  if docker network inspect "${LITELLM_NETWORK_NAME}" >/dev/null 2>&1; then
    owner="$(docker network inspect --format '{{ index .Labels "agent-platform.mvp-profile" }}' "${LITELLM_NETWORK_NAME}")"
    if [[ "${owner}" != "${PROFILE_NAME}" ]]; then
      printf 'refusing to reuse unmanaged network: %s\n' "${LITELLM_NETWORK_NAME}" >&2
      return 1
    fi
    return
  fi
  docker network create \
    --label "agent-platform.mvp-profile=${PROFILE_NAME}" \
    "${LITELLM_NETWORK_NAME}" >/dev/null
}

profile_has_containers() {
  docker ps --all --quiet --filter "label=com.docker.compose.project=${CORE_PROJECT}" | rg --quiet '.' ||
    docker ps --all --quiet --filter "label=com.docker.compose.project=${LITELLM_PROJECT}" | rg --quiet '.' ||
    docker ps --all --quiet --filter "label=com.docker.compose.project=${APP_PROJECT}" | rg --quiet '.'
}

remove_llm_network() {
  local owner
  if ! docker network inspect "${LITELLM_NETWORK_NAME}" >/dev/null 2>&1; then
    return
  fi
  owner="$(docker network inspect --format '{{ index .Labels "agent-platform.mvp-profile" }}' "${LITELLM_NETWORK_NAME}")"
  if [[ "${owner}" == "${PROFILE_NAME}" ]]; then
    docker network rm "${LITELLM_NETWORK_NAME}" >/dev/null
  fi
}

stop_profile() {
  local volume_args=()
  local failed=false
  if [[ "${MVP_PROFILE_REMOVE_VOLUMES:-false}" == "true" ]]; then
    volume_args+=(--volumes)
  fi
  if ! app_compose down --remove-orphans "${volume_args[@]}" >/dev/null 2>&1; then
    printf 'failed to stop MVP app stack: %s\n' "${APP_PROJECT}" >&2
    failed=true
  fi
  if ! litellm_compose down --remove-orphans "${volume_args[@]}" >/dev/null 2>&1; then
    printf 'failed to stop MVP LiteLLM stack: %s\n' "${LITELLM_PROJECT}" >&2
    failed=true
  fi
  if ! core_compose down --remove-orphans "${volume_args[@]}" >/dev/null 2>&1; then
    printf 'failed to stop MVP core stack: %s\n' "${CORE_PROJECT}" >&2
    failed=true
  fi
  if ! remove_llm_network; then
    printf 'failed to remove MVP LiteLLM network: %s\n' "${LITELLM_NETWORK_NAME}" >&2
    failed=true
  fi
  if [[ "${failed}" == "true" ]]; then
    return 1
  fi
  printf 'MVP profile stopped: %s\n' "${PROFILE_NAME}"
}

cleanup_failed_start() {
  local exit_code=$?
  trap - ERR INT TERM
  if [[ "${STARTED_FRESH}" == "true" ]]; then
    MVP_PROFILE_REMOVE_VOLUMES=true stop_profile >/dev/null 2>&1 || true
  fi
  printf 'MVP profile start failed safely: %s\n' "${PROFILE_NAME}" >&2
  exit "${exit_code}"
}

assert_service_healthy() {
  local stack="$1"
  local service="$2"
  local container_id state
  case "${stack}" in
    core) container_id="$(core_compose ps --quiet "${service}")" ;;
    litellm) container_id="$(litellm_compose ps --quiet "${service}")" ;;
    app) container_id="$(app_compose ps --quiet "${service}")" ;;
    *) printf 'unknown MVP stack: %s\n' "${stack}" >&2; return 2 ;;
  esac
  if [[ -z "${container_id}" ]]; then
    printf '%s service is missing: %s\n' "${stack}" "${service}" >&2
    return 1
  fi
  state="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "${container_id}")"
  if [[ "${state}" != "healthy" ]]; then
    printf '%s service is not healthy: %s (%s)\n' "${stack}" "${service}" "${state}" >&2
    return 1
  fi
  printf '%s service healthy: %s\n' "${stack}" "${service}"
}

health_profile() {
  local service
  for service in postgres redis minio; do
    assert_service_healthy core "${service}"
  done
  for service in litellm-db openai-stub litellm; do
    assert_service_healthy litellm "${service}"
  done
  for service in api dispatcher sandbox-controller sandbox-janitor worker frontend; do
    assert_service_healthy app "${service}"
  done
  PLATFORM_API_PORT="${PLATFORM_API_PORT}" PLATFORM_WEB_PORT="${PLATFORM_WEB_PORT}" \
    bash "${ROOT_DIR}/infra/platform/health.sh"
  printf 'MVP profile healthy (local Stub, RAGFlow excluded): %s\n' "${PROFILE_NAME}"
}

start_profile() {
  if ! profile_has_containers; then
    STARTED_FRESH=true
  fi
  trap cleanup_failed_start ERR INT TERM
  core_compose config --quiet
  litellm_compose config --quiet
  app_compose config --quiet
  ensure_llm_network
  core_compose up --detach --wait --wait-timeout 180 postgres redis minio
  litellm_compose up --detach --wait --wait-timeout 240 litellm openai-stub
  litellm_compose run --rm --no-deps worker-key-bootstrap
  app_compose up --detach --wait --wait-timeout 300 \
    migrate api dispatcher sandbox-controller sandbox-janitor worker frontend
  health_profile
  trap - ERR INT TERM
  printf 'MVP profile started: %s\n' "${PROFILE_NAME}"
}

status_profile() {
  printf 'Core services:\n'
  core_compose ps
  printf 'LiteLLM Stub services:\n'
  litellm_compose ps
  printf 'Platform services:\n'
  app_compose ps
}

validate_profile_name

case "${1:-status}" in
  start)
    write_environment
    load_environment
    start_profile
    ;;
  stop)
    if [[ -f "${CORE_ENV_FILE}" && -f "${LITELLM_ENV_FILE}" && -f "${PLATFORM_ENV_FILE}" ]]; then
      load_environment
      stop_profile
    else
      printf 'MVP profile already stopped: %s\n' "${PROFILE_NAME}"
    fi
    ;;
  health)
    load_environment
    health_profile
    ;;
  status)
    load_environment
    status_profile
    ;;
  *)
    printf 'usage: %s {start|stop|health|status}\n' "$0" >&2
    exit 2
    ;;
esac
