#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROFILE_NAME="agent-platform-mvp-test-$$"
RUNTIME_DIR="${ROOT_DIR}/.local/mvp-profile-tests/${PROFILE_NAME}"
MVP_SCRIPT="${ROOT_DIR}/infra/platform/mvp-profile.sh"

free_port() {
  python3 - <<'PY'
import socket

with socket.socket() as listener:
    listener.bind(("127.0.0.1", 0))
    print(listener.getsockname()[1])
PY
}

export MVP_PROFILE_NAME="${PROFILE_NAME}"
export MVP_PROFILE_RUNTIME_DIR="${RUNTIME_DIR}"
export MVP_PROFILE_REMOVE_VOLUMES=true
export POSTGRES_PORT="$(free_port)"
export REDIS_PORT="$(free_port)"
export MINIO_API_PORT="$(free_port)"
export MINIO_CONSOLE_PORT="$(free_port)"
export LITELLM_PORT="$(free_port)"
export PLATFORM_API_PORT="$(free_port)"
export PLATFORM_WEB_PORT="$(free_port)"

cleanup() {
  bash "${MVP_SCRIPT}" stop >/dev/null 2>&1 || true
  case "${RUNTIME_DIR}" in
    "${ROOT_DIR}"/.local/mvp-profile-tests/agent-platform-mvp-test-*)
      rm -rf "${RUNTIME_DIR}"
      ;;
    *)
      printf 'refusing to remove unsafe test runtime directory: %s\n' "${RUNTIME_DIR}" >&2
      ;;
  esac
}
trap cleanup EXIT

bash "${MVP_SCRIPT}" start
bash "${MVP_SCRIPT}" start
bash "${MVP_SCRIPT}" health

set -a
# The file is generated by mvp-profile.sh with shell-safe token_urlsafe values.
# shellcheck disable=SC1090
source "${RUNTIME_DIR}/litellm.env"
set +a
AGENT_PLATFORM_LLM_GATEWAY_URL="http://127.0.0.1:${LITELLM_PORT}/v1" \
  AGENT_PLATFORM_LLM_GATEWAY_API_KEY="${LITELLM_WORKER_API_KEY}" \
  uv run --project "${ROOT_DIR}/backend" --frozen --no-dev \
    python "${ROOT_DIR}/infra/litellm/worker_gateway_probe.py" "chat"

docker compose -p "${PROFILE_NAME}-litellm" \
  --env-file "${RUNTIME_DIR}/litellm.env" \
  -f "${ROOT_DIR}/infra/compose/litellm.yml" \
  -f "${ROOT_DIR}/infra/litellm/compose.stub.yml" \
  ps --status running --services | rg --quiet '^openai-stub$'

docker compose -p "${PROFILE_NAME}-app" \
  --env-file "${RUNTIME_DIR}/platform.env" \
  -f "${ROOT_DIR}/infra/compose/platform.yml" \
  --profile worker ps --status running --services | rg --quiet '^sandbox-controller$'
docker compose -p "${PROFILE_NAME}-app" \
  --env-file "${RUNTIME_DIR}/platform.env" \
  -f "${ROOT_DIR}/infra/compose/platform.yml" \
  --profile worker ps --status running --services | rg --quiet '^sandbox-janitor$'

if docker ps --filter "label=com.docker.compose.project=${PROFILE_NAME}-core" \
  --filter "label=com.docker.compose.service=ragflow" --quiet | rg --quiet '.'; then
  printf 'RAGFlow must not be part of the MVP profile\n' >&2
  exit 1
fi

docker compose -p "${PROFILE_NAME}-app" \
  --env-file "${RUNTIME_DIR}/platform.env" \
  -f "${ROOT_DIR}/infra/compose/platform.yml" \
  --profile worker stop api
if bash "${MVP_SCRIPT}" health >/dev/null 2>&1; then
  printf 'MVP health must fail when API is stopped\n' >&2
  exit 1
fi
bash "${MVP_SCRIPT}" start

bash "${MVP_SCRIPT}" stop
bash "${MVP_SCRIPT}" stop

for project in "${PROFILE_NAME}-core" "${PROFILE_NAME}-litellm" "${PROFILE_NAME}-app"; do
  if docker ps --all --quiet --filter "label=com.docker.compose.project=${project}" | rg --quiet '.'; then
    printf 'MVP test left containers behind for project: %s\n' "${project}" >&2
    exit 1
  fi
  if docker volume ls --quiet --filter "label=com.docker.compose.project=${project}" | rg --quiet '.'; then
    printf 'MVP test left volumes behind for project: %s\n' "${project}" >&2
    exit 1
  fi
done
if docker network inspect "${PROFILE_NAME}-llm" >/dev/null 2>&1; then
  printf 'MVP test left its LiteLLM network behind\n' >&2
  exit 1
fi
printf 'MVP profile start, health, idempotency and cleanup passed\n'
