from typing import Protocol
from uuid import UUID

from agent_platform.platform.artifacts.entities import (
    Artifact,
    File,
    StorageOperation,
    TaskAttachment,
)


class ArtifactStorageProvider(Protocol):
    async def put(self, *, key: str, content: bytes, media_type: str) -> None: ...

    async def get(self, *, key: str) -> bytes: ...

    async def delete(self, *, key: str) -> None: ...


class FileRepository(Protocol):
    async def add(self, file: File) -> None: ...

    async def get(self, *, tenant_id: UUID, file_id: UUID) -> File | None: ...

    async def delete(self, *, tenant_id: UUID, file_id: UUID) -> bool: ...


class TaskAttachmentRepository(Protocol):
    async def add(self, attachment: TaskAttachment) -> None: ...

    async def list_for_run(self, *, tenant_id: UUID, run_id: UUID) -> list[TaskAttachment]: ...


class ArtifactRepository(Protocol):
    async def add(self, artifact: Artifact) -> None: ...

    async def get(self, *, tenant_id: UUID, artifact_id: UUID) -> Artifact | None: ...

    async def list_for_run(self, *, tenant_id: UUID, run_id: UUID) -> list[Artifact]: ...

    async def delete(self, *, tenant_id: UUID, artifact_id: UUID) -> bool: ...


class StorageOperationRepository(Protocol):
    async def add(self, operation: StorageOperation) -> None: ...

    async def mark_status(self, *, operation_id: UUID, status: str) -> None: ...

    async def list_pending(self, *, limit: int = 100) -> list[StorageOperation]: ...


class ArtifactWorkspace(Protocol):
    async def write_file(self, *, path: str, content: bytes) -> None: ...

    async def read_file(self, *, path: str) -> bytes: ...
